import { ModeToggle } from "@/components/theme/ModeToggle";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Freelancer / Portfolio Templates</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="flex flex-col caret-transparent items-center justify-center min-h-[100vh] py-16 px-4 bg-gradient-to-br from-blue-50 via-cyan-100 to-blue-100 dark:from-gray-950 dark:via-gray-900 dark:to-blue-950">
        <div className="absolute top-4 right-4">
          <ModeToggle />
        </div>
        <h1 className="text-4xl md:text-5xl font-extrabold text-blue-900 dark:text-blue-100 mb-4 text-center drop-shadow-lg">
          Welcome to Freelancer Portfolio Templates
        </h1>
        <p className="text-lg md:text-xl text-blue-800 dark:text-blue-200 mb-8 text-center max-w-2xl">
          Elevate your freelance business with our modern, customizable
          portfolio templates. Showcase your skills, attract clients, and grow
          your brand with style and confidence.
        </p>
        <Link
          href="/auth"
          className="inline-block px-8 py-3 rounded-full bg-gradient-to-r from-cyan-600 via-sky-500 to-blue-700 text-yellow-200 font-bold text-lg shadow-lg hover:from-yellow-300 hover:to-yellow-400 hover:text-blue-900 transition-all duration-200"
        >
          Go to Auth Page
        </Link>
      </main>
    </>
  );
}
